export const CITY_MAP: Record<string, string[]> = {
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
    "Arnhem",
    "Haarlem",
    "Enschede",
    "Amersfoort",
    "Apeldoorn",
    "Leiden",
    "Delft",
    "Maastricht",
    "Zwolle",
    "Den Bosch",
  ],

  Belgium: [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Bruges",
    "Leuven",
    "Liège",
    "Namur",
    "Charleroi",
    "Mechelen",
    "Mons",
    "Hasselt",
    "Kortrijk",
    "Ostend",
    "Genk",
    "Tournai",
    "Roeselare",
    "Aalst",
    "Sint-Niklaas",
    "Ypres",
    "Waterloo",
  ],

  France: [
    "Paris",
    "Lyon",
    "Marseille",
    "Nice",
    "Toulouse",
    "Bordeaux",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Clermont-Ferrand",
  ],

  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Granada",
    "A Coruña",
    "Vitoria-Gasteiz",
    "Elche",
    "Oviedo",
  ],

  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Liverpool",
    "Leeds",
    "Glasgow",
    "Edinburgh",
    "Bristol",
    "Sheffield",
    "Newcastle",
    "Nottingham",
    "Leicester",
    "Southampton",
    "Brighton",
    "Cardiff",
    "Belfast",
    "Coventry",
    "Reading",
    "Oxford",
    "Cambridge",
  ],
};